import sql from "@/app/api/utils/sql";

// Send appraisal via email
export async function POST(request, { params }) {
  try {
    const { id } = params;
    const body = await request.json();
    const { recipientEmail, recipientName, message } = body;

    if (!recipientEmail) {
      return Response.json(
        { error: "Recipient email is required" },
        { status: 400 },
      );
    }

    // Get appraisal data
    const appraisal = await sql`
      SELECT * FROM appraisals WHERE id = ${id}
    `;

    if (appraisal.length === 0) {
      return Response.json({ error: "Appraisal not found" }, { status: 404 });
    }

    // Get company settings
    const settings = await sql`
      SELECT * FROM company_settings ORDER BY id DESC LIMIT 1
    `;

    const companySettings = settings[0] || {
      company_name: "Pulse Appraising",
      email: "contact@pulseappraising.com",
    };

    const vehicle = appraisal[0].vehicle_data;
    const vehicleTitle = `${vehicle.year} ${vehicle.make} ${vehicle.model}`;

    // TODO: Integrate with Resend API when ready
    // For now, we'll just log the email details
    const emailData = {
      from: companySettings.email,
      to: recipientEmail,
      subject: `Vehicle Appraisal: ${vehicleTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #06b6d4;">Vehicle Appraisal Report</h2>
          <p>Hello ${recipientName || "there"},</p>
          ${message ? `<p>${message}</p>` : ""}
          <div style="background: #1E293B; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #fff; margin-top: 0;">${vehicleTitle}</h3>
            <p style="color: #94a3b8;">VIN: ${appraisal[0].vin}</p>
            ${vehicle.price ? `<p style="color: #10b981; font-size: 24px; font-weight: bold;">$${vehicle.price.toLocaleString()}</p>` : ""}
          </div>
          <p style="color: #64748b; font-size: 12px;">
            This appraisal was generated by ${companySettings.company_name}<br>
            ${companySettings.phone ? `Phone: ${companySettings.phone}` : ""}
          </p>
        </div>
      `,
    };

    console.log("Email would be sent:", emailData);

    // Mark as emailed
    await sql`
      UPDATE appraisals
      SET email_sent = TRUE
      WHERE id = ${id}
    `;

    // When Resend is integrated, the code would be:
    /*
    const resendApiKey = process.env.RESEND_API_KEY;
    if (resendApiKey) {
      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${resendApiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(emailData)
      });
      
      if (!response.ok) {
        throw new Error('Failed to send email');
      }
    }
    */

    return Response.json({
      success: true,
      message: "Email sent successfully",
      note: "Email integration pending - configure RESEND_API_KEY",
    });
  } catch (error) {
    console.error("Error sending email:", error);
    return Response.json({ error: "Failed to send email" }, { status: 500 });
  }
}
