import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import pulseLogo from "@/assets/pulse-logo.png";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="border-b border-border/50 glass sticky top-0 z-50">
        <div className="max-w-4xl mx-auto flex items-center justify-between px-6 py-3">
          <Link to="/landing" className="flex items-center gap-2.5">
            <img src={pulseLogo} alt="Pulse Posting" className="h-9" />
          </Link>
          <Link to="/landing" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" /> Back
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-black tracking-tight text-foreground">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mt-2">Last updated: February 20, 2026</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-6 text-foreground/90 [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-foreground [&_h3]:mt-6 [&_h3]:mb-2 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_li]:text-sm [&_li]:text-muted-foreground [&_ul]:space-y-1 [&_ol]:space-y-1">

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using the Pulse: Post platform ("Service"), operated by Lotly Automotive Solutions LLC ("Company," "we," "us," or "our"), you ("User," "you," or "your") agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you may not access or use the Service. These Terms apply to all visitors, users, and others who access the Service, including dealership administrators ("Admins") and staff members ("Staff") invited by Admins.</p>

          <h2>2. Description of Service</h2>
          <p>Pulse: Post is a software-as-a-service (SaaS) platform designed for independent automotive dealerships. The Service provides tools for:</p>
          <ul className="list-disc pl-6">
            <li>Automated vehicle listing creation and management for Facebook Marketplace</li>
            <li>AI-powered vehicle description generation</li>
            <li>Dealer Management System (DMS) inventory synchronization</li>
            <li>Vehicle image optimization and sorting</li>
            <li>Lead capture and management from marketplace inquiries</li>
            <li>Staff management, performance tracking, and invitation systems</li>
            <li>Price intelligence and sold vehicle alert notifications</li>
          </ul>

          <h2>3. Account Registration & Eligibility</h2>
          <h3>3.1 Eligibility</h3>
          <p>You must be at least 18 years of age and have the legal authority to enter into these Terms. If you are registering on behalf of a business entity, you represent that you have the authority to bind that entity to these Terms.</p>
          <h3>3.2 Admin Accounts</h3>
          <p>The individual who registers a dealership account is automatically designated as the dealership administrator ("Admin"). The Admin is responsible for all activity under their dealership account, including the actions of any Staff members they invite. Each dealership receives a unique dealership identifier that cannot be shared or transferred between accounts.</p>
          <h3>3.3 Staff Accounts</h3>
          <p>Staff members may only join the platform via an invitation link generated by an Admin. Staff accounts are automatically linked to the Admin's dealership and have limited access as determined by the Admin. Staff members do not have access to administrative functions, settings, or billing information.</p>
          <h3>3.4 Account Security</h3>
          <p>You are responsible for maintaining the confidentiality of your login credentials. You agree to immediately notify us of any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to safeguard your account information.</p>

          <h2>4. Subscription Plans & Payment</h2>
          <h3>4.1 Plans</h3>
          <p>We offer subscription plans including Starter ($49/month) and Unlimited ($99/month). Plan features, pricing, and limits are subject to change with 30 days' notice. All plans include a 7-day free trial period.</p>
          <h3>4.2 Billing</h3>
          <p>Subscription fees are billed monthly in advance. Payment is processed through our third-party payment processor. You authorize us to charge your designated payment method on a recurring basis. All fees are non-refundable except as required by applicable law or as stated in our refund policy.</p>
          <h3>4.3 Cancellation</h3>
          <p>You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period. No prorated refunds are provided for partial months.</p>

          <h2>5. Acceptable Use Policy</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6">
            <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations</li>
            <li>Post false, misleading, or fraudulent vehicle listings</li>
            <li>Misrepresent vehicle conditions, mileage, history, or pricing</li>
            <li>Upload or transmit malicious code, viruses, or harmful content</li>
            <li>Attempt to gain unauthorized access to any portion of the Service</li>
            <li>Use the Service to spam, harass, or send unsolicited communications</li>
            <li>Reverse engineer, decompile, or disassemble any portion of the Service</li>
            <li>Share login credentials or invite links with unauthorized individuals</li>
            <li>Violate Facebook Marketplace's terms of service or community standards</li>
            <li>Use automated bots or scripts to interact with the Service beyond its intended API</li>
          </ul>

          <h2>6. Content & Intellectual Property</h2>
          <h3>6.1 Your Content</h3>
          <p>You retain ownership of all vehicle data, images, and information you upload to the Service ("Your Content"). By uploading Your Content, you grant us a non-exclusive, worldwide, royalty-free license to use, process, and display Your Content solely for the purpose of providing the Service.</p>
          <h3>6.2 AI-Generated Content</h3>
          <p>Vehicle descriptions and other content generated by our AI tools are created for your use. You are responsible for reviewing all AI-generated content for accuracy and compliance before publishing. We do not guarantee the accuracy, completeness, or legal compliance of AI-generated content.</p>
          <h3>6.3 Our Intellectual Property</h3>
          <p>The Service, including its design, features, code, trademarks, and documentation, is owned by Lotly Automotive Solutions LLC and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works of the Service without our express written consent.</p>

          <h2>7. Third-Party Integrations</h2>
          <p>The Service integrates with third-party platforms including Facebook Marketplace, DMS providers, and other services. We are not responsible for the availability, accuracy, or policies of third-party services. Your use of third-party integrations is subject to their respective terms of service. We do not guarantee that third-party integrations will remain available or function without interruption.</p>

          <h2>8. Data & Privacy</h2>
          <p>Your use of the Service is also governed by our <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>, which is incorporated into these Terms by reference. By using the Service, you consent to the collection, use, and sharing of your information as described in our Privacy Policy.</p>

          <h2>9. Disclaimers & Limitation of Liability</h2>
          <h3>9.1 Disclaimer of Warranties</h3>
          <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY OF INFORMATION.</p>
          <h3>9.2 Limitation of Liability</h3>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, LOTLY AUTOMOTIVE SOLUTIONS LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>

          <h2>10. Indemnification</h2>
          <p>You agree to indemnify, defend, and hold harmless Lotly Automotive Solutions LLC, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including reasonable attorneys' fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any content you upload, post, or transmit through the Service.</p>

          <h2>11. Termination</h2>
          <p>We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service ceases immediately. Sections relating to intellectual property, limitation of liability, indemnification, and governing law survive termination.</p>

          <h2>12. Governing Law & Dispute Resolution</h2>
          <p>These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Any disputes arising from these Terms or the Service shall be resolved through binding arbitration administered by the American Arbitration Association in Dallas, Texas. You waive your right to participate in a class action lawsuit or class-wide arbitration.</p>

          <h2>13. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Material changes will be communicated via email or through the Service with at least 30 days' notice. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the updated Terms.</p>

          <h2>14. Contact Information</h2>
          <p>For questions about these Terms, please contact us at:</p>
          <p>Lotly Automotive Solutions LLC<br />Email: legal@pulseposting.com<br />Address: 430 E 8th St #5157, Holland, MI 49423</p>
        </div>
      </main>
    </div>
  );
}
